name: test

on: 
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install --no-audit --no-fund --no-optional
      - name: Run test db
        run: npm run test:db
      - name: Run test models
        run: npm run test:models
      - name: Run test controllers
        run: npm run test:controllers
      - name: Run test routes
        run: npm run test:routes