name: Test API

on: 
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: List folders
        run: cd api && ls 